-- 1. Tabla Principal de Estudiantes
CREATE TABLE estudiantes (
  id bigint generated by default as identity primary key,
  cedula text unique not null,
  nombre text,
  apellido text,
  correo text,
  carrera text,
  curso text,          -- Equivale al semestre/nivel
  jornada text,
  promedio numeric,
  deuda numeric,       -- Si es mayor a 0, tiene deuda
  matriculado boolean, -- true o false
  asistencia_porc numeric, -- Porcentaje de asistencia (ej: 95)
  horas_practicas integer  -- Horas acumuladas (ej: 120)
);

-- 2. Tabla de Detalle de Notas (Relacionada por cédula)
CREATE TABLE notas_detalle (
  id bigint generated by default as identity primary key,
  cedula_estudiante text references estudiantes(cedula),
  materia text,
  parcial_1 numeric,
  parcial_2 numeric,
  nota_final numeric
);

-- 3. Tabla de Registro de Solicitudes (Logs del Bot)
CREATE TABLE solicitudes (
  id bigint generated by default as identity primary key,
  cedula_estudiante text,
  tipo_certificado text,
  fecha_solicitud timestamp with time zone default timezone('utc'::text, now())
);